<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="hibernate.cfg.xml" />
    <None Remove="Mappins\Cliente.hbm.xml" />
    <None Remove="Mappins\Divida.hbm.xml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="hibernate.cfg.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Mappins\Cliente.hbm.xml" />
    <EmbeddedResource Include="Mappins\Divida.hbm.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cpf" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="NHibernate" Version="5.5.2" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

</Project>
